### ISSUE TITLE
empty settings and macros

### ISSUE THREAD

**Issue by St007** [mmone/OctoprintKlipperPlugin#11]
Installed plugin on Octoprint Version 1.3.9, Klipper Firmware version: v0.6.0-339-g3f59c3d
Running on latest Armbian.
After install I can't open klipper config (it is just empty), all settings in plugin empty, default emergency stop macro empty too. The only thing working  - panel buttons like "get status", "firmware restart". However Performance Graph is empty too (no files in dropdown file selector)

**Comment by mmone** [comment]
I currently test only on octopi so some paths might be different there.

> After install I can't open klipper config (it is just empty)

You can change the path the plugin is looking for the "printer.cfg" in the settings.

> all settings in plugin empty

That I can't explain atm. The emergency macro exists but the "GCODE" field is empty?
Can you create new macros and are they persistent if you save the settings?

> However Performance Graph is empty too (no files in dropdown file selector)

The plugin looks for logfiles in /tmp/ namped klippy.log* are they also located there for your install?

In any case it would help if you could post an octoprint.log. On a standard octopi installation this is located at "/home/pi/.octoprint/logs/octoprint.log"

**Comment by arminth** [comment]
In a standard install, the klippy.log ist found here: /tmp/klippy.log
I also don't get no filechoice for the perfgraph!
Cheers
Armin

**Comment by St007** [comment]
more details:
1. I used plugin on another armbian with more old Octoprint, Klipper and plugin version and it works there out the box, till now.
2. I have added path to printer.cfg without any effect
3. Emergency macro is empty, there is no any macros after fresh install
4. Log file on my machine is /tmp/klippy.log
log file attached
[octoprint.log](https://github.com/mmone/OctoprintKlipperPlugin/files/2288509/octoprint.log)

**Comment by mmone** [comment]
> In a standard install, the klippy.log ist found here: /tmp/klippy.log
> I also don't get no filechoice for the perfgraph!

That is interesting. Could you verify that you have logs in /tmp/ at the moment. 
If so reload you octoprint in the browser as the listing is only done once when loading the page at the moment

**Comment by St007** [comment]
Yes, I can add the path, but it just not works ...not sure if it is hard to detect current user's home path and look for printer.cfg there instead of trying to load  '/home/pi/printer.cfg'

**Comment by mmone** [comment]
Yes that would be possible an absolute path seemed more flexible. Last thing you could try after checking whether the path displayed in the UI is correct is to restart Octoprint as the settings are only read on startup at the moment.

**Comment by St007** [comment]
Yes, the path in settings exists after Octoprint restart, that was the first I tried to do :)

**Comment by mmone** [comment]
I'm trying to reproduce the issue. What is you actual path?

**Comment by St007** [comment]
actual path /home/slv/printer.cfg
I guess it is in octoprint log too

**Comment by mmone** [comment]
If you still willing to debug some more you could check your Octoprint config file. 
For me this is located at ~/.octoprint/config.yaml
That is where the plugin stores its settings. The should be an entry:

```
  klipper:
    _config_version: 2
    configuration:
      path: /home/slv/printer.cfg
```

**Comment by St007** [comment]
```
  klipper:
    _config_version: 2
  softwareupdate:
    _config_version: 6
    check_providers:
      fanspeedslider: fanspeedslider
      klipper: klipper
printerProfiles:
  default: _default
serial:
  additionalPorts:
  - /tmp/printer
  autoconnect: true
  disconnectOnErrors: false
  port: /tmp/printer
server:
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: F0yaRdQAGtdQmY7DCRop9dJNK2qmZ4lO
  seenWizards:
    corewizard: 3
    cura: null
```

**Comment by mmone** [comment]
OK. I think I can reproduce the issue know. It's a bug. As a quick fix you could manually add the correct path to the config.yaml like that then the rest of the default config should load as well. I will provide a bugfix release soon.

```
  klipper:
    _config_version: 2
    configuration:
      path: /home/slv/printer.cfg
```
